apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-06-11T09:21:27Z
  generation: 1
  labels:
    run: hello-dotnet
  name: hello-dotnet
  namespace: test
  resourceVersion: "8169"
  selfLink: /apis/extensions/v1beta1/namespaces/test/deployments/hello-dotnet
  uid: d1cf67ae-6d58-11e8-897b-6665d995e746
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-dotnet
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-dotnet
    spec:
      containers:
      - image: sugendh/dotnetcorebmb:latest
        imagePullPolicy: Always
        name: hello-dotnet
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-06-11T09:21:28Z
    lastUpdateTime: 2018-06-11T09:21:28Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1